global:
  scrape_interval: 3s
  scrape_timeout: 3s
  evaluation_interval: 1s

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 5s
      api_version: v1
scrape_configs:

  - job_name: my_proxy
    honor_timestamps: true
    scrape_interval: 3s
    scrape_timeout: 3s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:9000
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 2s
    scrape_timeout: 2s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
