use hashbrown::HashMap;
use std::sync::OnceLock;

pub const DEFAULT_CHARSET: &str = "utf8mb4";
pub const DEFAULT_COLLATION_NAME: &str = "utf8_general_ci";

pub const DEFAULT_COLLATION_ID: u8 = 46;
pub const LATIN1DEFAULT_COLLATION_ID: u8 = 47;
pub const ASCII_DEFAULT_COLLATION_ID: u8 = 65;
pub const UTF8DEFAULT_COLLATION_ID: u8 = 83;
pub const UTF8MB4_DEFAULT_COLLATION_ID: u8 = 46;
pub const BINARY_DEFAULT_COLLATION_ID: u8 = 63;
pub const OK_PACKET_HEADER_BIT: u8 = 0x00;
pub const ERR_PACKET_HEADER_BIT: u8 = 0xff;
pub const UTF8_MB4_GENERAL_CI: u8 = 45;

pub fn collations() -> &'static HashMap<u8, &'static str> {
    static COLLATIONS: OnceLock<HashMap<u8, &str>> = OnceLock::new();
    COLLATIONS.get_or_init(|| {
        let mut collations = HashMap::new();
        collations.insert(1, "big5_chinese_ci");
        collations.insert(2, "latin2_czech_cs");
        collations.insert(3, "dec8_swedish_ci");
        collations.insert(4, "cp850_general_ci");
        collations.insert(5, "latin1_german1_ci");
        collations.insert(6, "hp8_english_ci");
        collations.insert(7, "koi8r_general_ci");
        collations.insert(8, "latin1_swedish_ci");
        collations.insert(9, "latin2_general_ci");
        collations.insert(10, "swe7_swedish_ci");
        collations.insert(11, "ascii_general_ci");
        collations.insert(12, "ujis_japanese_ci");
        collations.insert(13, "sjis_japanese_ci");
        collations.insert(14, "cp1251_bulgarian_ci");
        collations.insert(15, "latin1_danish_ci");
        collations.insert(16, "hebrew_general_ci");
        collations.insert(18, "tis620_thai_ci");
        collations.insert(19, "euckr_korean_ci");
        collations.insert(20, "latin7_estonian_cs");
        collations.insert(21, "latin2_hungarian_ci");
        collations.insert(22, "koi8u_general_ci");
        collations.insert(23, "cp1251_ukrainian_ci");
        collations.insert(24, "gb2312_chinese_ci");
        collations.insert(25, "greek_general_ci");
        collations.insert(26, "cp1250_general_ci");
        collations.insert(27, "latin2_croatian_ci");
        collations.insert(28, "gbk_chinese_ci");
        collations.insert(29, "cp1257_lithuanian_ci");
        collations.insert(30, "latin5_turkish_ci");
        collations.insert(31, "latin1_german2_ci");
        collations.insert(32, "armscii8_general_ci");
        collations.insert(33, "utf8_general_ci");
        collations.insert(34, "cp1250_czech_cs");
        collations.insert(35, "ucs2_general_ci");
        collations.insert(36, "cp866_general_ci");
        collations.insert(37, "keybcs2_general_ci");
        collations.insert(38, "macce_general_ci");
        collations.insert(39, "macroman_general_ci");
        collations.insert(40, "cp852_general_ci");
        collations.insert(41, "latin7_general_ci");
        collations.insert(42, "latin7_general_cs");
        collations.insert(43, "macce_bin");
        collations.insert(44, "cp1250_croatian_ci");
        collations.insert(45, "utf8mb4_general_ci");
        collations.insert(46, "utf8mb4_bin");
        collations.insert(47, "latin1_bin");
        collations.insert(48, "latin1_general_ci");
        collations.insert(49, "latin1_general_cs");
        collations.insert(50, "cp1251_bin");
        collations.insert(51, "cp1251_general_ci");
        collations.insert(52, "cp1251_general_cs");
        collations.insert(53, "macroman_bin");
        collations.insert(54, "utf16_general_ci");
        collations.insert(55, "utf16_bin");
        collations.insert(56, "utf16le_general_ci");
        collations.insert(57, "cp1256_general_ci");
        collations.insert(58, "cp1257_bin");
        collations.insert(59, "cp1257_general_ci");
        collations.insert(60, "utf32_general_ci");
        collations.insert(61, "utf32_bin");
        collations.insert(62, "utf16le_bin");
        collations.insert(63, "binary");
        collations.insert(64, "armscii8_bin");
        collations.insert(65, "ascii_bin");
        collations.insert(66, "cp1250_bin");
        collations.insert(67, "cp1256_bin");
        collations.insert(68, "cp866_bin");
        collations.insert(69, "dec8_bin");
        collations.insert(70, "greek_bin");
        collations.insert(71, "hebrew_bin");
        collations.insert(72, "hp8_bin");
        collations.insert(73, "keybcs2_bin");
        collations.insert(74, "koi8r_bin");
        collations.insert(75, "koi8u_bin");
        collations.insert(77, "latin2_bin");
        collations.insert(78, "latin5_bin");
        collations.insert(79, "latin7_bin");
        collations.insert(80, "cp850_bin");
        collations.insert(81, "cp852_bin");
        collations.insert(82, "swe7_bin");
        collations.insert(83, "utf8_bin");
        collations.insert(84, "big5_bin");
        collations.insert(85, "euckr_bin");
        collations.insert(86, "gb2312_bin");
        collations.insert(87, "gbk_bin");
        collations.insert(88, "sjis_bin");
        collations.insert(89, "tis620_bin");
        collations.insert(90, "ucs2_bin");
        collations.insert(91, "ujis_bin");
        collations.insert(92, "geostd8_general_ci");
        collations.insert(93, "geostd8_bin");
        collations.insert(94, "latin1_spanish_ci");
        collations.insert(95, "cp932_japanese_ci");
        collations.insert(96, "cp932_bin");
        collations.insert(97, "eucjpms_japanese_ci");
        collations.insert(98, "eucjpms_bin");
        collations.insert(99, "cp1250_polish_ci");
        collations.insert(101, "utf16_unicode_ci");
        collations.insert(102, "utf16_icelandic_ci");
        collations.insert(103, "utf16_latvian_ci");
        collations.insert(104, "utf16_romanian_ci");
        collations.insert(105, "utf16_slovenian_ci");
        collations.insert(106, "utf16_polish_ci");
        collations.insert(107, "utf16_estonian_ci");
        collations.insert(108, "utf16_spanish_ci");
        collations.insert(109, "utf16_swedish_ci");
        collations.insert(110, "utf16_turkish_ci");
        collations.insert(111, "utf16_czech_ci");
        collations.insert(112, "utf16_danish_ci");
        collations.insert(113, "utf16_lithuanian_ci");
        collations.insert(114, "utf16_slovak_ci");
        collations.insert(115, "utf16_spanish2_ci");
        collations.insert(116, "utf16_roman_ci");
        collations.insert(117, "utf16_persian_ci");
        collations.insert(118, "utf16_esperanto_ci");
        collations.insert(119, "utf16_hungarian_ci");
        collations.insert(120, "utf16_sinhala_ci");
        collations.insert(121, "utf16_german2_ci");
        collations.insert(122, "utf16_croatian_ci");
        collations.insert(123, "utf16_unicode_520_ci");
        collations.insert(124, "utf16_vietnamese_ci");
        collations.insert(128, "ucs2_unicode_ci");
        collations.insert(129, "ucs2_icelandic_ci");
        collations.insert(130, "ucs2_latvian_ci");
        collations.insert(131, "ucs2_romanian_ci");
        collations.insert(132, "ucs2_slovenian_ci");
        collations.insert(133, "ucs2_polish_ci");
        collations.insert(134, "ucs2_estonian_ci");
        collations.insert(135, "ucs2_spanish_ci");
        collations.insert(136, "ucs2_swedish_ci");
        collations.insert(137, "ucs2_turkish_ci");
        collations.insert(138, "ucs2_czech_ci");
        collations.insert(139, "ucs2_danish_ci");
        collations.insert(140, "ucs2_lithuanian_ci");
        collations.insert(141, "ucs2_slovak_ci");
        collations.insert(142, "ucs2_spanish2_ci");
        collations.insert(143, "ucs2_roman_ci");
        collations.insert(144, "ucs2_persian_ci");
        collations.insert(145, "ucs2_esperanto_ci");
        collations.insert(146, "ucs2_hungarian_ci");
        collations.insert(147, "ucs2_sinhala_ci");
        collations.insert(148, "ucs2_german2_ci");
        collations.insert(149, "ucs2_croatian_ci");
        collations.insert(150, "ucs2_unicode_520_ci");
        collations.insert(151, "ucs2_vietnamese_ci");
        collations.insert(159, "ucs2_general_mysql500_ci");
        collations.insert(160, "utf32_unicode_ci");
        collations.insert(161, "utf32_icelandic_ci");
        collations.insert(162, "utf32_latvian_ci");
        collations.insert(163, "utf32_romanian_ci");
        collations.insert(164, "utf32_slovenian_ci");
        collations.insert(165, "utf32_polish_ci");
        collations.insert(166, "utf32_estonian_ci");
        collations.insert(167, "utf32_spanish_ci");
        collations.insert(168, "utf32_swedish_ci");
        collations.insert(169, "utf32_turkish_ci");
        collations.insert(170, "utf32_czech_ci");
        collations.insert(171, "utf32_danish_ci");
        collations.insert(172, "utf32_lithuanian_ci");
        collations.insert(173, "utf32_slovak_ci");
        collations.insert(174, "utf32_spanish2_ci");
        collations.insert(175, "utf32_roman_ci");
        collations.insert(176, "utf32_persian_ci");
        collations.insert(177, "utf32_esperanto_ci");
        collations.insert(178, "utf32_hungarian_ci");
        collations.insert(179, "utf32_sinhala_ci");
        collations.insert(180, "utf32_german2_ci");
        collations.insert(181, "utf32_croatian_ci");
        collations.insert(182, "utf32_unicode_520_ci");
        collations.insert(183, "utf32_vietnamese_ci");
        collations.insert(192, "utf8_unicode_ci");
        collations.insert(193, "utf8_icelandic_ci");
        collations.insert(194, "utf8_latvian_ci");
        collations.insert(195, "utf8_romanian_ci");
        collations.insert(196, "utf8_slovenian_ci");
        collations.insert(197, "utf8_polish_ci");
        collations.insert(198, "utf8_estonian_ci");
        collations.insert(199, "utf8_spanish_ci");
        collations.insert(200, "utf8_swedish_ci");
        collations.insert(201, "utf8_turkish_ci");
        collations.insert(202, "utf8_czech_ci");
        collations.insert(203, "utf8_danish_ci");
        collations.insert(204, "utf8_lithuanian_ci");
        collations.insert(205, "utf8_slovak_ci");
        collations.insert(206, "utf8_spanish2_ci");
        collations.insert(207, "utf8_roman_ci");
        collations.insert(208, "utf8_persian_ci");
        collations.insert(209, "utf8_esperanto_ci");
        collations.insert(210, "utf8_hungarian_ci");
        collations.insert(211, "utf8_sinhala_ci");
        collations.insert(212, "utf8_german2_ci");
        collations.insert(213, "utf8_croatian_ci");
        collations.insert(214, "utf8_unicode_520_ci");
        collations.insert(215, "utf8_vietnamese_ci");
        collations.insert(223, "utf8_general_mysql500_ci");
        collations.insert(224, "utf8mb4_unicode_ci");
        collations.insert(225, "utf8mb4_icelandic_ci");
        collations.insert(226, "utf8mb4_latvian_ci");
        collations.insert(227, "utf8mb4_romanian_ci");
        collations.insert(228, "utf8mb4_slovenian_ci");
        collations.insert(229, "utf8mb4_polish_ci");
        collations.insert(230, "utf8mb4_estonian_ci");
        collations.insert(231, "utf8mb4_spanish_ci");
        collations.insert(232, "utf8mb4_swedish_ci");
        collations.insert(233, "utf8mb4_turkish_ci");
        collations.insert(234, "utf8mb4_czech_ci");
        collations.insert(235, "utf8mb4_danish_ci");
        collations.insert(236, "utf8mb4_lithuanian_ci");
        collations.insert(237, "utf8mb4_slovak_ci");
        collations.insert(238, "utf8mb4_spanish2_ci");
        collations.insert(239, "utf8mb4_roman_ci");
        collations.insert(240, "utf8mb4_persian_ci");
        collations.insert(241, "utf8mb4_esperanto_ci");
        collations.insert(242, "utf8mb4_hungarian_ci");
        collations.insert(243, "utf8mb4_sinhala_ci");
        collations.insert(244, "utf8mb4_german2_ci");
        collations.insert(245, "utf8mb4_croatian_ci");
        collations.insert(246, "utf8mb4_unicode_520_ci");
        collations.insert(247, "utf8mb4_vietnamese_ci");
        collations.insert(255, "utf8mb4_0900_ai_ci");

        collations
    })
}

//  maps MySQL collation name to its ID
pub fn collation_names() -> &'static HashMap<&'static str, u8> {
    static COLLATION_NAMES: OnceLock<HashMap<&str, u8>> = OnceLock::new();
    COLLATION_NAMES.get_or_init(|| {
        let mut collation_names = HashMap::new();
        collation_names.insert("big5_chinese_ci", 1);
        collation_names.insert("latin2_czech_cs", 2);
        collation_names.insert("dec8_swedish_ci", 3);
        collation_names.insert("cp850_general_ci", 4);
        collation_names.insert("latin1_german1_ci", 5);
        collation_names.insert("hp8_english_ci", 6);
        collation_names.insert("koi8r_general_ci", 7);
        collation_names.insert("latin1_swedish_ci", 8);
        collation_names.insert("latin2_general_ci", 9);
        collation_names.insert("swe7_swedish_ci", 10);
        collation_names.insert("ascii_general_ci", 11);
        collation_names.insert("ujis_japanese_ci", 12);
        collation_names.insert("sjis_japanese_ci", 13);
        collation_names.insert("cp1251_bulgarian_ci", 14);
        collation_names.insert("latin1_danish_ci", 15);
        collation_names.insert("hebrew_general_ci", 16);
        collation_names.insert("tis620_thai_ci", 18);
        collation_names.insert("euckr_korean_ci", 19);
        collation_names.insert("latin7_estonian_cs", 20);
        collation_names.insert("latin2_hungarian_ci", 21);
        collation_names.insert("koi8u_general_ci", 22);
        collation_names.insert("cp1251_ukrainian_ci", 23);
        collation_names.insert("gb2312_chinese_ci", 24);
        collation_names.insert("greek_general_ci", 25);
        collation_names.insert("cp1250_general_ci", 26);
        collation_names.insert("latin2_croatian_ci", 27);
        collation_names.insert("gbk_chinese_ci", 28);
        collation_names.insert("cp1257_lithuanian_ci", 29);
        collation_names.insert("latin5_turkish_ci", 30);
        collation_names.insert("latin1_german2_ci", 31);
        collation_names.insert("armscii8_general_ci", 32);
        collation_names.insert("utf8_general_ci", 33);
        collation_names.insert("cp1250_czech_cs", 34);
        collation_names.insert("ucs2_general_ci", 35);
        collation_names.insert("cp866_general_ci", 36);
        collation_names.insert("keybcs2_general_ci", 37);
        collation_names.insert("macce_general_ci", 38);
        collation_names.insert("macroman_general_ci", 39);
        collation_names.insert("cp852_general_ci", 40);
        collation_names.insert("latin7_general_ci", 41);
        collation_names.insert("latin7_general_cs", 42);
        collation_names.insert("macce_bin", 43);
        collation_names.insert("cp1250_croatian_ci", 44);
        collation_names.insert("utf8mb4_general_ci", 45);
        collation_names.insert("utf8mb4_bin", 46);
        collation_names.insert("latin1_bin", 47);
        collation_names.insert("latin1_general_ci", 48);
        collation_names.insert("latin1_general_cs", 49);
        collation_names.insert("cp1251_bin", 50);
        collation_names.insert("cp1251_general_ci", 51);
        collation_names.insert("cp1251_general_cs", 52);
        collation_names.insert("macroman_bin", 53);
        collation_names.insert("utf16_general_ci", 54);
        collation_names.insert("utf16_bin", 55);
        collation_names.insert("utf16le_general_ci", 56);
        collation_names.insert("cp1256_general_ci", 57);
        collation_names.insert("cp1257_bin", 58);
        collation_names.insert("cp1257_general_ci", 59);
        collation_names.insert("utf32_general_ci", 60);
        collation_names.insert("utf32_bin", 61);
        collation_names.insert("utf16le_bin", 62);
        collation_names.insert("binary", 63);
        collation_names.insert("armscii8_bin", 64);
        collation_names.insert("ascii_bin", 65);
        collation_names.insert("cp1250_bin", 66);
        collation_names.insert("cp1256_bin", 67);
        collation_names.insert("cp866_bin", 68);
        collation_names.insert("dec8_bin", 69);
        collation_names.insert("greek_bin", 70);
        collation_names.insert("hebrew_bin", 71);
        collation_names.insert("hp8_bin", 72);
        collation_names.insert("keybcs2_bin", 73);
        collation_names.insert("koi8r_bin", 74);
        collation_names.insert("koi8u_bin", 75);
        collation_names.insert("latin2_bin", 77);
        collation_names.insert("latin5_bin", 78);
        collation_names.insert("latin7_bin", 79);
        collation_names.insert("cp850_bin", 80);
        collation_names.insert("cp852_bin", 81);
        collation_names.insert("swe7_bin", 82);
        collation_names.insert("utf8_bin", 83);
        collation_names.insert("big5_bin", 84);
        collation_names.insert("euckr_bin", 85);
        collation_names.insert("gb2312_bin", 86);
        collation_names.insert("gbk_bin", 87);
        collation_names.insert("sjis_bin", 88);
        collation_names.insert("tis620_bin", 89);
        collation_names.insert("ucs2_bin", 90);
        collation_names.insert("ujis_bin", 91);
        collation_names.insert("geostd8_general_ci", 92);
        collation_names.insert("geostd8_bin", 93);
        collation_names.insert("latin1_spanish_ci", 94);
        collation_names.insert("cp932_japanese_ci", 95);
        collation_names.insert("cp932_bin", 96);
        collation_names.insert("eucjpms_japanese_ci", 97);
        collation_names.insert("eucjpms_bin", 98);
        collation_names.insert("cp1250_polish_ci", 99);
        collation_names.insert("utf16_unicode_ci", 101);
        collation_names.insert("utf16_icelandic_ci", 102);
        collation_names.insert("utf16_latvian_ci", 103);
        collation_names.insert("utf16_romanian_ci", 104);
        collation_names.insert("utf16_slovenian_ci", 105);
        collation_names.insert("utf16_polish_ci", 106);
        collation_names.insert("utf16_estonian_ci", 107);
        collation_names.insert("utf16_spanish_ci", 108);
        collation_names.insert("utf16_swedish_ci", 109);
        collation_names.insert("utf16_turkish_ci", 110);
        collation_names.insert("utf16_czech_ci", 111);
        collation_names.insert("utf16_danish_ci", 112);
        collation_names.insert("utf16_lithuanian_ci", 113);
        collation_names.insert("utf16_slovak_ci", 114);
        collation_names.insert("utf16_spanish2_ci", 115);
        collation_names.insert("utf16_roman_ci", 116);
        collation_names.insert("utf16_persian_ci", 117);
        collation_names.insert("utf16_esperanto_ci", 118);
        collation_names.insert("utf16_hungarian_ci", 119);
        collation_names.insert("utf16_sinhala_ci", 120);
        collation_names.insert("utf16_german2_ci", 121);
        collation_names.insert("utf16_croatian_ci", 122);
        collation_names.insert("utf16_unicode_520_ci", 123);
        collation_names.insert("utf16_vietnamese_ci", 124);
        collation_names.insert("ucs2_unicode_ci", 128);
        collation_names.insert("ucs2_icelandic_ci", 129);
        collation_names.insert("ucs2_latvian_ci", 130);
        collation_names.insert("ucs2_romanian_ci", 131);
        collation_names.insert("ucs2_slovenian_ci", 132);
        collation_names.insert("ucs2_polish_ci", 133);
        collation_names.insert("ucs2_estonian_ci", 134);
        collation_names.insert("ucs2_spanish_ci", 135);
        collation_names.insert("ucs2_swedish_ci", 136);
        collation_names.insert("ucs2_turkish_ci", 137);
        collation_names.insert("ucs2_czech_ci", 138);
        collation_names.insert("ucs2_danish_ci", 139);
        collation_names.insert("ucs2_lithuanian_ci", 140);
        collation_names.insert("ucs2_slovak_ci", 141);
        collation_names.insert("ucs2_spanish2_ci", 142);
        collation_names.insert("ucs2_roman_ci", 143);
        collation_names.insert("ucs2_persian_ci", 144);
        collation_names.insert("ucs2_esperanto_ci", 145);
        collation_names.insert("ucs2_hungarian_ci", 146);
        collation_names.insert("ucs2_sinhala_ci", 147);
        collation_names.insert("ucs2_german2_ci", 148);
        collation_names.insert("ucs2_croatian_ci", 149);
        collation_names.insert("ucs2_unicode_520_ci", 150);
        collation_names.insert("ucs2_vietnamese_ci", 151);
        collation_names.insert("ucs2_general_mysql500_ci", 159);
        collation_names.insert("utf32_unicode_ci", 160);
        collation_names.insert("utf32_icelandic_ci", 161);
        collation_names.insert("utf32_latvian_ci", 162);
        collation_names.insert("utf32_romanian_ci", 163);
        collation_names.insert("utf32_slovenian_ci", 164);
        collation_names.insert("utf32_polish_ci", 165);
        collation_names.insert("utf32_estonian_ci", 166);
        collation_names.insert("utf32_spanish_ci", 167);
        collation_names.insert("utf32_swedish_ci", 168);
        collation_names.insert("utf32_turkish_ci", 169);
        collation_names.insert("utf32_czech_ci", 170);
        collation_names.insert("utf32_danish_ci", 171);
        collation_names.insert("utf32_lithuanian_ci", 172);
        collation_names.insert("utf32_slovak_ci", 173);
        collation_names.insert("utf32_spanish2_ci", 174);
        collation_names.insert("utf32_roman_ci", 175);
        collation_names.insert("utf32_persian_ci", 176);
        collation_names.insert("utf32_esperanto_ci", 177);
        collation_names.insert("utf32_hungarian_ci", 178);
        collation_names.insert("utf32_sinhala_ci", 179);
        collation_names.insert("utf32_german2_ci", 180);
        collation_names.insert("utf32_croatian_ci", 181);
        collation_names.insert("utf32_unicode_520_ci", 182);
        collation_names.insert("utf32_vietnamese_ci", 183);
        collation_names.insert("utf8_unicode_ci", 192);
        collation_names.insert("utf8_icelandic_ci", 193);
        collation_names.insert("utf8_latvian_ci", 194);
        collation_names.insert("utf8_romanian_ci", 195);
        collation_names.insert("utf8_slovenian_ci", 196);
        collation_names.insert("utf8_polish_ci", 197);
        collation_names.insert("utf8_estonian_ci", 198);
        collation_names.insert("utf8_spanish_ci", 199);
        collation_names.insert("utf8_swedish_ci", 200);
        collation_names.insert("utf8_turkish_ci", 201);
        collation_names.insert("utf8_czech_ci", 202);
        collation_names.insert("utf8_danish_ci", 203);
        collation_names.insert("utf8_lithuanian_ci", 204);
        collation_names.insert("utf8_slovak_ci", 205);
        collation_names.insert("utf8_spanish2_ci", 206);
        collation_names.insert("utf8_roman_ci", 207);
        collation_names.insert("utf8_persian_ci", 208);
        collation_names.insert("utf8_esperanto_ci", 209);
        collation_names.insert("utf8_hungarian_ci", 210);
        collation_names.insert("utf8_sinhala_ci", 211);
        collation_names.insert("utf8_german2_ci", 212);
        collation_names.insert("utf8_croatian_ci", 213);
        collation_names.insert("utf8_unicode_520_ci", 214);
        collation_names.insert("utf8_vietnamese_ci", 215);
        collation_names.insert("utf8_general_mysql500_ci", 223);
        collation_names.insert("utf8mb4_unicode_ci", 224);
        collation_names.insert("utf8mb4_icelandic_ci", 225);
        collation_names.insert("utf8mb4_latvian_ci", 226);
        collation_names.insert("utf8mb4_romanian_ci", 227);
        collation_names.insert("utf8mb4_slovenian_ci", 228);
        collation_names.insert("utf8mb4_polish_ci", 229);
        collation_names.insert("utf8mb4_estonian_ci", 230);
        collation_names.insert("utf8mb4_spanish_ci", 231);
        collation_names.insert("utf8mb4_swedish_ci", 232);
        collation_names.insert("utf8mb4_turkish_ci", 233);
        collation_names.insert("utf8mb4_czech_ci", 234);
        collation_names.insert("utf8mb4_danish_ci", 235);
        collation_names.insert("utf8mb4_lithuanian_ci", 236);
        collation_names.insert("utf8mb4_slovak_ci", 237);
        collation_names.insert("utf8mb4_spanish2_ci", 238);
        collation_names.insert("utf8mb4_roman_ci", 239);
        collation_names.insert("utf8mb4_persian_ci", 240);
        collation_names.insert("utf8mb4_esperanto_ci", 241);
        collation_names.insert("utf8mb4_hungarian_ci", 242);
        collation_names.insert("utf8mb4_sinhala_ci", 243);
        collation_names.insert("utf8mb4_german2_ci", 244);
        collation_names.insert("utf8mb4_croatian_ci", 245);
        collation_names.insert("utf8mb4_unicode_520_ci", 246);
        collation_names.insert("utf8mb4_vietnamese_ci", 247);
        collation_names.insert("utf8mb4_0900_ai_ci", 255);
        collation_names
    })
}

pub fn charsets() -> &'static HashMap<&'static str, &'static str> {
    static CHARSETS: OnceLock<HashMap<&str, &str>> = OnceLock::new();
    CHARSETS.get_or_init(|| {
        let mut charsets = HashMap::new();
        charsets.insert("big5", "big5_chinese_ci");
        charsets.insert("dec8", "dec8_swedish_ci");
        charsets.insert("cp850", "cp850_general_ci");
        charsets.insert("hp8", "hp8_english_ci");
        charsets.insert("koi8r", "koi8r_general_ci)");
        charsets.insert("latin1", "latin1_swedish_ci");
        charsets.insert("latin2", "latin2_general_ci)");
        charsets.insert("swe7", "swe7_swedish_ci)");
        charsets.insert("ascii", "ascii_general_ci)");
        charsets.insert("ujis", "ujis_japanese_ci");
        charsets.insert("sjis", "sjis_japanese_ci");
        charsets.insert("hebrew", "hebrew_general_ci");
        charsets.insert("tis620", "tis620_thai_ci");
        charsets.insert("euckr", "euckr_korean_ci");
        charsets.insert("koi8u", "koi8u_general_ci");
        charsets.insert("gb2312", "gb2312_chinese_ci");
        charsets.insert("greek", "greek_general_ci");
        charsets.insert("cp1250", "cp1250_general_ci");
        charsets.insert("gbk", "gbk_chinese_ci");
        charsets.insert("latin5", "latin5_turkish_ci");
        charsets.insert("armscii8", "armscii8_general_ci");
        charsets.insert("utf8", "utf8_general_ci");
        charsets.insert("ucs2", "ucs2_general_ci");
        charsets.insert("cp866", "cp866_general_ci");
        charsets.insert("keybcs2", "keybcs2_general_ci");
        charsets.insert("macce", "macce_general_ci");
        charsets.insert("macroman", "macroman_general_ci");
        charsets.insert("cp852", "cp852_general_ci");
        charsets.insert("latin7", "latin7_general_ci");
        charsets.insert("utf8mb4", "utf8mb4_general_ci");
        charsets.insert("cp1251", "cp1251_general_ci");
        charsets.insert("utf16", "utf16_general_ci");
        charsets.insert("utf16le", "utf16le_general_ci");
        charsets.insert("cp1256", "cp1256_general_ci");
        charsets.insert("cp1257", "cp1257_general_ci");
        charsets.insert("utf32", "utf32_general_ci");
        charsets.insert("binary", "binary");
        charsets.insert("geostd8", "geostd8_general_ci");
        charsets.insert("cp932", "cp932_japanese_ci");
        charsets.insert("eucjpms", "eucjpms_japanese_ci");
        charsets
    })
}

// fast path
pub fn get_charset_id(charset_name: &str) -> u8 {
    match charset_name {
        "utf8mb4" => DEFAULT_COLLATION_ID,
        "binary" => BINARY_DEFAULT_COLLATION_ID,
        "utf8" => UTF8DEFAULT_COLLATION_ID,
        "ascii" => ASCII_DEFAULT_COLLATION_ID,
        "latin1" => LATIN1DEFAULT_COLLATION_ID,
        _ => (*charset_ids().get(charset_name).unwrap())
            .try_into()
            .unwrap(),
    }
}
// maps charset name to its default collation ID.
pub fn charset_ids() -> &'static HashMap<&'static str, u16> {
    static CHARSET_IDS: OnceLock<HashMap<&str, u16>> = OnceLock::new();
    CHARSET_IDS.get_or_init(|| {
        let mut charset_ids = HashMap::new();
        charset_ids.insert("big5", 1);
        charset_ids.insert("dec8", 3);
        charset_ids.insert("cp850", 4);
        charset_ids.insert("hp8", 6);
        charset_ids.insert("koi8r", 7);
        charset_ids.insert("latin1", 8);
        charset_ids.insert("latin2", 9);
        charset_ids.insert("swe7", 10);
        charset_ids.insert("ascii", 11);
        charset_ids.insert("ujis", 12);
        charset_ids.insert("sjis", 13);
        charset_ids.insert("hebrew", 16);
        charset_ids.insert("tis620", 18);
        charset_ids.insert("euckr", 19);
        charset_ids.insert("koi8u", 22);
        charset_ids.insert("gb2312", 24);
        charset_ids.insert("greek", 25);
        charset_ids.insert("cp1250", 26);
        charset_ids.insert("gbk", 28);
        charset_ids.insert("latin5", 30);
        charset_ids.insert("armscii8", 32);
        charset_ids.insert("utf8", 33);
        charset_ids.insert("ucs2", 35);
        charset_ids.insert("cp866", 36);
        charset_ids.insert("keybcs2", 37);
        charset_ids.insert("macce", 38);
        charset_ids.insert("macroman", 39);
        charset_ids.insert("cp852", 40);
        charset_ids.insert("latin7", 41);
        charset_ids.insert("utf8mb4", 45);
        charset_ids.insert("cp1251", 51);
        charset_ids.insert("utf16", 54);
        charset_ids.insert("utf16le", 56);
        charset_ids.insert("cp1256", 57);
        charset_ids.insert("cp1257", 59);
        charset_ids.insert("utf32", 60);
        charset_ids.insert("binary", 63);
        charset_ids.insert("geostd8", 92);
        charset_ids.insert("cp932", 95);
        charset_ids.insert("eucjpms", 97);
        charset_ids
    })
}

#[cfg(test)]
mod tests {
    use crate::protocol::mysql::charset::charset_ids;

    #[test]
    pub fn charset_ids_test() {
        let utf8mb4_id_val = 45_u16;
        let utf8mb4_id = charset_ids().get("utf8mb4");
        assert!(utf8mb4_id.is_some());
        assert_eq!(utf8mb4_id_val, utf8mb4_id.unwrap().clone());
    }
}
