{
 "title": "MyProxy Cluster overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node Name", "query": { "query": "label_values(node_name)" } },
   { "name": "SQLCom", "label": "proxy_com", "query": { "query": "label_values(proxy_com)" } }
  ]
 },
 "panels": [
  {
   "title": "ProxyCPUCore",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_process_cpu_core_num{node_name=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ProxyCPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "proxy_process_cpu_seconds_total{node_name=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ProxyRSSMem",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "proxy_process_mem_rss_bytes{node_name=\"PangMacbookM1.local\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ProxyMaxConn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "proxy_max_connections{node_name=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ProxyCurrConns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "proxy_curr_connections{node_name=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQLComLatency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(proxy_com_latency_bucket{proxy_com=~\"ComQuery|ComStmtExecute|ComStmtPrepare\"}[$__rate_interval])) by (le, node, proxy_com))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(proxy_com_latency_bucket{node_name=~\"$node\", proxy_com=\"ComInitDB\"}[$__rate_interval])))",
     "legendFormat": "ComInitDB"
    }
   ]
  }
 ]
}